def location_name_to_game_id(input):
    name_to_id = {
        "Vacation Beach - Block The Sun": "CoolDownSunTanBot",
        "Vacation Beach - R e l a x": "DoYoga",
        "Vacation Beach - Good At Sports I": "BeatSportSet_Set1",
        "Vacation Beach - Good At Sports II": "BeatSportSet_Set2",
        "Vacation Beach - Beach Bugs": "FindBeachBugs",
        "Vacation Beach - Sandcastles I": "CompleteAllSandCastles_Basic",
        "Vacation Beach - Sandcastles II": "CompleteAllSandCastles_Beginner",
        "Vacation Beach - Sandcastles III": "CompleteAllSandCastles_Intermediate",
        "Vacation Beach - Sandcastles IV": "CompleteAllSandCastles_Advanced",
        "Vacation Beach - Sandcastles V": "CompleteAllSandCastles_Master",
        "Vacation Beach - Sweet Selfie": "HandInDiveBotSelfie",
        "Dive Site - Sea Shanty": "DiveSite_PlaySeaShanty",
        "Dive Site - Open BotBeard's Treasure": "DiveSite_OpenTreasureChest",
        "Dive Site - Sea Life Snaps I": "DiveSite_SeaLifePhotography_Set1",
        "Dive Site - Sea Life Snaps II": "DiveSite_SeaLifePhotography_Set2",
        "Vacation Beach - Beach Orders I": "BeachFoodOrders_GetMemorySet1",
        "Vacation Beach - Beach Orders II": "BeachFoodOrders_GetMemorySet2",
        "Vacation Beach - Beach Orders III": "BeachFoodOrders_GetMemorySet3",
        "Vacation Beach - Beach Orders IV": "BeachFoodOrders_GetMemorySet4",
        "Vacation Beach - Beach Photos I": "FinishPostcardCollection_Beach_1",
        "Vacation Beach - Beach Photos II": "FinishPostcardCollection_Beach_2",
        "Vacation Beach - Beach Photos III": "FinishPostcardCollection_Beach_3",
        "Vacation Beach - Beach Photos IV": "FinishPostcardCollection_Beach_4",
        "Vacation Forest - Fish Finder I": "RiverFishOrders_Set1",
        "Vacation Forest - Fish Finder II": "RiverFishOrders_Set2",
        "Vacation Forest - Fish Finder III": "RiverFishOrders_Set3",
        "Vacation Forest - Painting I": "FinishPaintingsI",
        "Vacation Forest - Painting II": "FinishPaintingsII",
        "Vacation Forest - Forest Bugs": "FindForestBugs",
        "Vacation Forest - Forest Targets": "ForestTargetsAll_SpeakToBot",
        "Vacation Forest - Beach Targets": "BeachTargetsAll_SpeakToBot",
        "Vacation Forest - Mountain Targets": "MountainTargetsAll_SpeakToBot",
        "Vacation Forest - Spooky Story": "ListenedToMultiPartCampfireStory",
        "Vacation Forest - Garden Variety": "CompletePlanting",
        "Vacation Forest - Forest Orders I": "ForestFoodOrders_GetMemorySet1",
        "Vacation Forest - Forest Orders II": "ForestFoodOrders_GetMemorySet2",
        "Vacation Forest - Forest Orders III": "ForestFoodOrders_GetMemorySet3",
        "Vacation Forest - Forest Orders IV": "ForestFoodOrders_GetMemorySet4",
        "Hiking Trail - Skipping ROCKS": "CompleteRockSkippingHighScore",
        "Hiking Trail - Bird Observer": "CompletedBirdWatching",
        "Hiking Trail - Hike Selfie": "TakePictureAtHikingPhotoBooth",
        "Hiking Trail - Turn On Geyser": "CompleteGeyser",
        "Vacation Forest - Raft Master": "FinishRaftingGame_AllLevels",
        "Vacation Forest - Forest Photos I": "FinishPostcardCollection_Forest_1",
        "Vacation Forest - Forest Photos II": "FinishPostcardCollection_Forest_2",
        "Vacation Forest - Forest Photos III": "FinishPostcardCollection_Forest_3",
        "Vacation Forest - Forest Photos IV": "FinishPostcardCollection_Forest_4",
        "Vacation Mountain - Warm Winter": "GiveWaterToWarmBot",
        "Vacation Mountain - Knitted Gift": "DeliverKnitBotKnitGift",
        "Vacation Mountain - Good Listener": "ListenToHotTubMonologue",
        "Vacation Mountain - Mountain Orders I": "MountainFoodOrders_GetMemorySet1",
        "Vacation Mountain - Mountain Orders II": "MountainFoodOrders_GetMemorySet2",
        "Vacation Mountain - Mountain Orders III": "MountainFoodOrders_GetMemorySet3",
        "Vacation Mountain - Mountain Orders IV": "MountainFoodOrders_GetMemorySet4",
        "Vacation Mountain - Puzzle Master": "CompleteJigsawPuzzle",
        "Vacation Mountain - Ice Sculptures I": "CompleteAllIceSculptures_101",
        "Vacation Mountain - Ice Sculptures II": "CompleteAllIceSculptures_Beginner",
        "Vacation Mountain - Ice Sculptures III": "CompleteAllIceSculptures_Intermediate",
        "Vacation Mountain - Ice Sculptures IV": "CompleteAllIceSculptures_Advanced",
        "Vacation Mountain - Ice Sculptures V": "CompleteAllIceSculptures_Master",
        "Vacation Mountain - Snow Safety Lesson": "SnowThrowingCompleteAllSigns",
        "Vacation Mountain - Mountain Bugs": "FindMountainBugs",
        "Vacation Mountain - Photobombinable": "TurnInPhotobombinableSnowBotPhoto",
        "Overlook - On Hill Skiing I": "FinishSkiing1",
        "Overlook - On Hill Skiing II": "FinishSkiing2",
        "Overlook - Mountain Climbing I": "FinishClimbingGame1",
        "Overlook - Mountain Climbing II": "FinishClimbingGame2",
        "Overlook - Raise Flag At Summit": "CompleteSummit",
        "Vacation Mountain - Mountain Photos I": "FinishPostcardCollection_Mountain_1",
        "Vacation Mountain - Mountain Photos II": "FinishPostcardCollection_Mountain_2",
        "Vacation Mountain - Mountain Photos III": "FinishPostcardCollection_Mountain_3",
        "Vacation Mountain - Mountain Photos IV": "FinishPostcardCollection_Mountain_4",
    }

    return name_to_id[input]
